name: 🐱 Digital Cat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Скачиваем код
      uses: actions/checkout@v4

    - name: Устанавливаем Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Проверяем, что игра запускается (Эмуляция игрока)
      shell: bash
      run: |
        printf "FelineFantasy\n0\n" | timeout 10s python Digital_Cat.py
